# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  kaleo.dev:
    site_hosts:
      - canonical: kaleo.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: robbyking3@gmail.com
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
    env:
      domain_current_site: kaleo.dev