# Documentation: https://roots.io/trellis/docs/local-development-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/development/vault.yml

wordpress_sites:
  give.tabelchurch.ca:
    site_hosts:
      - canonical: kaleo.dev
        redirects:
          - www.example.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    admin_email: robbyking3@gmail.com
    multisite:
      enabled: true
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
